# Numpy属性

In [3]:
# 基于莫烦python教程

import numpy as np

# 列表转化为矩阵
array = np.array([[1, 2, 3], [2, 3, 4]])# 列表转为矩阵
print(array)

# numpy的属性
# ndim：维度
# shape：行数和列数
# size：元素个数

print('number of dim:', array.ndim)# 维度

print('shape:', array.shape) # 行数和列数

print('size:', array.size) # 元素个数

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


# Numpy的创建 array

In [11]:
# 关键字
# array 创建数组
# dtype 指定数据类型
# zeros 创建数据全为0
# ones 创建数据全为1
# empty 创建数据接近0
# arrange 按指定范围创建数据
# linspace 创建线段


# 创建数组
a = np.array([2, 23, 4])# list 1d
print(a)

# 指定数据 dtype
a = np.array([2, 23, 4], dtype=np.int)
print(a.dtype)

a = np.array([2, 23, 4], dtype=np.int32)
print(a.dtype)

a = np.array([2, 23, 4], dtype=np.float)
print(a.dtype)

a = np.array([2, 23, 4], dtype=np.float32)
print(a.dtype)


# 创建特定数据
a = np.array([[2, 23, 4],[2, 32, 4]])# 2d 矩阵 2行3列
print(a)

# 创建全1数组,指定特定数据类型
a = np.ones((3, 4), dtype=np.int)
print(a)

# 创建全空数组，其实每个值都是接近于0的数\
a = np.empty((3, 4))
print(a)

# 使用arange创建连续数组
a = np.arange(10, 20, 2) # 10-19数据， 2步长
print(a)

# 使用reshape改变数组的形状
a = np.arange(12).reshape((3, 4)) # 3行4列， 0-11
print(a)

# 用linsapce创建线段型数据
a = np.linspace(1, 10, 20) # 开始端1，结束端10，分割成20个数据，生成线段
print(a)

# 在使用linspace基础上进行reshape工作
a = np.linspace(1, 10, 20).reshape((5, 4)) # 更改reshape
print(a)

[ 2 23  4]
int64
int32
float64
float32
[[ 2 23  4]
 [ 2 32  4]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324 5.e-324]]
[10 12 14 16 18]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


# Numpy基础运算1

In [19]:
a = np.array([10, 20, 30, 40])
print(a)
b = np.arange(4)
print(b)

# 减法
c = a - b
print(c)

# 加法
c = a + b
print(c)

# 乘法
c = a * b
print(c)

# 求某个矩阵里各个元素的乘方
c = b ** 2
print(c)

# sin函数
c = 10 * np.sin(a)
print(c)

# 对矩阵进行逻辑判断
print(b < 3)

## 上面是一维矩阵的操作，下面请看多维矩阵的运算
a = np.array([[1, 1],[0, 1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

# 矩阵的标准乘法运算
c_dot = np.dot(a, b)
print(c_dot)
c_dot_2 = a.dot(b)# 另一种表示方法

# random的使用
a = np.random.random((2, 4)) # 生成一个2行4列的矩阵，其中每一个元素都在0-1之间
print(a)

# sum(), min(), max()使用
print(np.sum(a))
print(np.min(a))
print(np.max(a))

# 对特定的行或列进行查找，使用axis
# axis = 0==>以列为查找单元； axis = 1==>以行为查找单元
print("sum = ", np.sum(a, axis=1))
print("min = ", np.min(a, axis=0))
print("max = ", np.max(a, axis=1))

[10 20 30 40]
[0 1 2 3]
[10 19 28 37]
[10 21 32 43]
[  0  20  60 120]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]
[ True  True  True False]
[[1 1]
 [0 1]]
[[0 1]
 [2 3]]
[[2 4]
 [2 3]]
[[0.42041952 0.11430183 0.97826769 0.97023249]
 [0.39263942 0.59905525 0.45962651 0.45904226]]
4.393584956819083
0.1143018273785088
0.9782676871429201
sum =  [2.48322152 1.91036344]
min =  [0.39263942 0.11430183 0.45962651 0.45904226]
max =  [0.97826769 0.59905525]


# Numpy 基础运算2

In [30]:
A = np.arange(2, 14).reshape((3, 4))
print(A)

# 求解矩阵中最小元素和最大元素的索引
# argmin(), argmax()
print(np.argmin(A))
print(np.argmax(A))

# 计算均值
print(np.mean(A))# 也可以写成 A.mean()
print(np.average(A))

# 求解中位数
print(np.median(A)) # A.median()

# 累加函数
print(np.cumsum(A))
# 在cumsum()函数中：生成的每一项矩阵元素均是从原矩阵首项累加到对应项的元素之和。比如元素9，在cumsum()生成的矩阵中序号为3，即原矩阵中2，3，4三个元素的和。

# 累差函数
print(np.diff(A))
# 该函数计算的便是每一行中后一项与前一项之差。故一个3行4列矩阵通过函数计算得到的矩阵便是3行3列的矩阵。

# nonzero()函数
print(np.nonzero(A))
# 这个函数将所有非零元素的行与列坐标分割开，重构成两个分别关于行和列的矩阵

# 排序操作
A = np.arange(14, 2, -1).reshape((3, 4))
print(A)
print(np.sort(A))
# 排序函数仍然仅针对每一行进行从小到大排序操作

# 矩阵的转置
print(np.transpose(A))# A.T也可以

# clip()函数
# 这个函数的格式是clip(Array,Array_min,Array_max)
# 顾名思义，Array指的是将要被执行用的矩阵，
# 后面的最小值最大值则用于让函数判断矩阵中元素是否有比最小值小的或者比最大值大的元素
# 并将这些指定的元素转换为最小值或者最大值。
print(np.clip(A, 5, 9))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


# Numpy 索引

In [43]:
# 一维索引

A = np.arange(3, 15)
print(A)
print(A[6])

# 二维索引
A = np.arange(3, 15).reshape((3, 4))
print(A)
print(A[2])
print(A[2][2])
# 也可以用
print(A[2, 2])

# numpy中的切片操作
print(A[1, 1 : 3]) # 切片1:3输出1-2的元素
# 这一表示形式即针对第二行中第2到第4列元素进行切片输出（不包含第4列）

# 利用for进行打印
for row in A:
    print(row)

for column in np.transpose(A):
    print(column)
for column in A.T:
    print(column)
# 上述表示方法即对A进行转置，再将得到的矩阵逐行输出即可得到原矩阵的逐列输出

# 迭代输出问题
A = np.arange(3, 15).reshape((3, 4))
print(A)
print(A.flatten())

for item in A.flat:
    print(item)
print(A.flat)
# 这一脚本中的flatten是一个展开性质的函数，将多维的矩阵进行展开成1行的数列
# flat是一个迭代器，本身是一个object属性

[ 3  4  5  6  7  8  9 10 11 12 13 14]
9
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
13
13
[8 9]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


# Numpy array 合并

In [58]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])

# vertical stack  上下合并
print(np.vstack((A, B)))

C = np.vstack((A, B))
print(A.shape, C.shape)

# horizontal stack 左右合并
D = np.hstack((A, B))
print(D)
print(A.shape, D.shape)

# np.newaxis()
# 关于newaxis的一点点理解：https://blog.csdn.net/molu_chase/article/details/78619731
print(A)
print(A[np.newaxis, :])
print(A[np.newaxis, :].shape)
print(A[np.newaxis, np.newaxis, :])

print(A[:, np.newaxis])

# 综合练习
A = np.array([1, 1, 1])[:, np.newaxis] #(3, 1)
print(A)
B = np.array([2, 2, 2])[:, np.newaxis]
print(B)

C = np.vstack((A, B))
print(C)
D = np.hstack((A, B))
print(D)


# np.concatenate()
# 当你要操作多个矩阵或序列时，使用concatenate()会很有用
# axis=0==》列；  axis=1==》行
C = np.concatenate((A, B, B, A), axis = 0)
print(C)

D = np.concatenate((A, B, B, A), axis = 1)
print(D)

[[1 1 1]
 [2 2 2]]
(3,) (2, 3)
[1 1 1 2 2 2]
(3,) (6,)
[1 1 1]
[[1 1 1]]
(1, 3)
[[[1 1 1]]]
[[1]
 [1]
 [1]]
[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


# Numpy array 分割

In [67]:
# 创建数据
A = np.arange(12).reshape((3, 4))
print(A)

# 纵向分割
print(np.split(A, 2, axis=1))

# 横向分割
print(np.split(A, 3, axis=0))

# 错误的分割
# 范例的Array只有4列，只能等量对分，因此输入以下程序代码后Python就会报错
# print(np.split(A, 3, axis=1)) # 报错

# 注意np.split()函数中 axis=1代表纵向分割；axis=0代表横向分割，和之前有点不同

# 不等量分割
print(np.array_split(A, 3, axis=1))

# np.vsplit()
print(np.vsplit(A, 3))#等于 print(np.split(A, 3, axis=0))

# np.hsplit()
print(np.hsplit(A, 2))#等于 print(np.split(A, 2, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# Numpy copy & deep copy

In [70]:
# = 的赋值方式会带有关联性
# 这里我想是虽是不同变量但是是指向同一地址
a = np.arange(4)
print(a)

b = a
c = a
d = a

# 改变a的第一个值，b、c、d的第一个值也会同时改变
a[0] = 11
print(b is a)
print(c is a)
print(d is a)
# 同样更改d的值，a、b、c也会改变

# copy()的赋值方式没有关联性
b = a.copy() # deep copy
print(b)
a[3] = 44
print(a is b)
print(a)
print(b)

[0 1 2 3]
True
True
True
[11  1  2  3]
False
[11  1  2 44]
[11  1  2  3]
